#ifndef QMAPINTERACTIVE_GLOBAL_H__
#define QMAPINTERACTIVE_GLOBAL_H__

#include <QtCore/qglobal.h>

#ifdef QMAPINTERACTIVE_LIB
# define QMAPINTERACTIVE_EXPORT Q_DECL_EXPORT
#else
# define QMAPINTERACTIVE_EXPORT Q_DECL_IMPORT
#endif


#endif // QMAPINTERACTIVE_GLOBAL_H__
